spring.application.name=demo

spring.data.mongodb.uri=mongodb://localhost:27017/bookmyshow
spring.data.mongodb.database=bookmyshow
server.port=8090

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s
